# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "faf0d7a36fc7910b0c24e38d5e234b6a"
name = "PTI Size Chart Pro"
handle = "sizechartpro-1"
application_url = "https://fate-seats-losing-mesh.trycloudflare.com"
embedded = true

[build]
automatically_update_urls_on_dev = true
dev_store_url = "gifting4.myshopify.com"
include_config_on_deploy = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_files,read_locales,read_products,read_themes,write_files,write_themes"

[auth]
redirect_urls = [
  "https://fate-seats-losing-mesh.trycloudflare.com/auth/callback",
  "https://fate-seats-losing-mesh.trycloudflare.com/auth/shopify/callback",
  "https://fate-seats-losing-mesh.trycloudflare.com/api/auth/callback"
]

[webhooks]
api_version = "2024-04"

[pos]
embedded = false
