# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "faf0d7a36fc7910b0c24e38d5e234b6a"
name = "SizeChartPro"
handle = "sizechartpro-1"
application_url = "https://platinum-salem-builders-homes.trycloudflare.com"
embedded = true

[build]
automatically_update_urls_on_dev = true
dev_store_url = "gifting4.myshopify.com"
include_config_on_deploy = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_locales,read_products"

[auth]
redirect_urls = [
  "https://platinum-salem-builders-homes.trycloudflare.com/auth/callback",
  "https://platinum-salem-builders-homes.trycloudflare.com/auth/shopify/callback",
  "https://platinum-salem-builders-homes.trycloudflare.com/api/auth/callback"
]

[webhooks]
api_version = "2024-04"

[pos]
embedded = false
